Client can create athletes
CraftAcademy/bn-invitational-backend pull request #10
Opened 2018-04-04 19:06 UTC by holgertidemand

#### PT Story: https://www.pivotaltracker.com/story/show/156421631
#### Description
Changes proposed in this pull request:

* adds ability for clients to create athletes 

#### What I have learned working on this feature: 
- To write clean code
- Plan better in design sprint

2018-04-04 19:07 UTC, kmthorsnes commented on app/controllers/api/v1/athletes_controller.rb
> +    render json: { status: 'Thank you for your vote.' } if @result.updated_votes(params)
Suggestion for next update: "Thank you for casting your vote!"

2018-04-04 19:10 UTC, kmthorsnes requested changes

2018-04-04 19:10 UTC, kmthorsnes commented on app/controllers/api/v1/athletes_controller.rb
> +    render json: { status: message}
space missing?

2018-04-04 19:10 UTC, kmthorsnes commented on spec/requests/api/v1/create_athlete_spec.rb
> +
remove whitespace

2018-04-04 19:14 UTC, kmthorsnes approved these changes
Looks good!

2018-04-05 08:45 UTC, davidboll approved these changes
LGTM

2018-04-05 08:49 UTC, merged